# https://doc.rust-lang.org/std/env/consts/constant.ARCH.html
archs:
  - x86_64:
      - amd64
  - aarch64:
      - arm64

github-bins:
  - "ClementTsang/bottom":
      # 在最后安装时链接到bin的名字
      name: btm
      # 为空时默认使用all releasees中的最新可能包含prerelease
      ver: latest
      path: ~/.local/bin
      exe-glob: btm
      hook:
        work-dir: .
        at:
          update: bash -c ''
          install:
          extract: 
