version: "3"

services:
  test:
    build:
      dockerfile: test.Dockerfile
    container_name: binaries
    env_file:
      - .env
    volumes:
      - ./target/release/binaries:/usr/local/bin/binaries
      - ./config.toml:/config.toml
    command: sh -c 'set -e;
      export PATH="$PATH:/root/.local/bin";
      binaries -vvvv -f /config.toml install;
      clash -v && hugo version;

      binaries -vvvv -f /config.toml uninstall -a;
      ! which clash && which hugo;
      '
